Route error messages to stderr

diff --git a/sinatra-gen b/sinatra-gen
--- a/sinatra-gen
+++ b/sinatra-gen
@@ -28,14 +28,14 @@ while [[ "$1" == -* ]]; do
       help
       exit;;
     -*)
-      echo "  ${red}ERROR: UNKNOWN ARGUMENT ($1)${clr}"
+      echo "  ${red}ERROR: UNKNOWN ARGUMENT ($1)${clr}" >&2
       help
       exit 1;;
   esac
 done
 
 if [[ -d $1 ]]; then
-  echo "  ${red}ERROR: DIRECTORY $1 ALREADY EXISTS${clr}"
+  echo "  ${red}ERROR: DIRECTORY $1 ALREADY EXISTS${clr}" >&2
   help
   exit 1
 else
