Create the directory if it doesn't exist
Otherwise we throw an error in pretty red.

diff --git a/sinatra-gen b/sinatra-gen
--- a/sinatra-gen
+++ b/sinatra-gen
@@ -33,3 +33,11 @@ while [[ "$1" == -* ]]; do
       exit 1;;
   esac
 done
+
+if [[ -d $1 ]]; then
+  echo "  ${red}ERROR: DIRECTORY $1 ALREADY EXISTS${clr}"
+  help
+  exit 1
+else
+  mkdir $1
+fi
